"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ChevronDown, Mail, Plus, Save, Trash2, Users } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Reminder={id:string;title:string;subject:string;notes:string|null;starts_at:string;recurrence:"none"|"daily"|"weekly"|"monthly"|"yearly";recipient_emails:string[];sender_email:string;active:boolean};
const recurrenceLabels:Record<Reminder["recurrence"],string>={none:"Does not repeat",daily:"Daily",weekly:"Weekly",monthly:"Monthly",yearly:"Yearly"};
const parseEmails=(value:string)=>Array.from(new Set(value.split(/[;,\n]/).map(e=>e.trim()).filter(Boolean)));

export default function RemindersPage(){
  const router=useRouter();const supabase=useMemo(()=>createClient(),[]);
  const [reminders,setReminders]=useState<Reminder[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [savingSettings,setSavingSettings]=useState(false);const [message,setMessage]=useState("");const [showForm,setShowForm]=useState(false);const [showEmailSettings,setShowEmailSettings]=useState(false);
  const [title,setTitle]=useState("");const [subject,setSubject]=useState("");const [notes,setNotes]=useState("");const [startsAt,setStartsAt]=useState("");const [recurrence,setRecurrence]=useState<Reminder["recurrence"]>("none");const [recipients,setRecipients]=useState("");const [primaryEmail,setPrimaryEmail]=useState("");const [complianceRecipients,setComplianceRecipients]=useState("");
  async function getUser(){for(let i=0;i<6;i++){const {data}=await supabase.auth.getSession();if(data.session?.user)return data.session.user;await new Promise(r=>setTimeout(r,150));}return null;}
  async function load(){setLoading(true);const user=await getUser();if(!user){router.replace("/");return;}setPrimaryEmail(user.email??"");const [r,p]=await Promise.all([supabase.from("family_reminders").select("id,title,subject,notes,starts_at,recurrence,recipient_emails,sender_email,active").order("starts_at",{ascending:true}),supabase.from("reminder_preferences").select("compliance_recipient_emails").eq("user_id",user.id).maybeSingle()]);if(r.error)setMessage(r.error.message);else setReminders((r.data??[]) as Reminder[]);if(p.error)setMessage(p.error.message);else setComplianceRecipients(((p.data?.compliance_recipient_emails??[]) as string[]).join(", "));setLoading(false);}
  useEffect(()=>{load();},[]);
  async function saveRecipients(){setSavingSettings(true);const user=await getUser();if(!user){router.replace("/");return;}const extra=parseEmails(complianceRecipients).filter(e=>e.toLowerCase()!==(user.email??"").toLowerCase());const {error}=await supabase.from("reminder_preferences").upsert({user_id:user.id,email_enabled:true,reminder_days:[30,7,2],compliance_recipient_emails:extra,updated_at:new Date().toISOString()},{onConflict:"user_id"});setMessage(error?error.message:"Email settings saved.");if(!error)setComplianceRecipients(extra.join(", "));setSavingSettings(false);}
  async function saveReminder(e:FormEvent){e.preventDefault();setSaving(true);const user=await getUser();if(!user){router.replace("/");return;}const {error}=await supabase.from("family_reminders").insert({user_id:user.id,title:title.trim(),subject:subject.trim(),notes:notes.trim()||null,starts_at:new Date(startsAt).toISOString(),next_send_at:new Date(startsAt).toISOString(),recurrence,recipient_emails:parseEmails(recipients),sender_email:"tuan.pi@gmail.com"});if(error)setMessage(error.message);else{setTitle("");setSubject("");setNotes("");setStartsAt("");setRecurrence("none");setRecipients("");setShowForm(false);setMessage("Reminder saved.");await load();}setSaving(false);}
  async function remove(id:string){if(!confirm("Delete this reminder?"))return;const {error}=await supabase.from("family_reminders").delete().eq("id",id);if(error)setMessage(error.message);else await load();}
  const extras=parseEmails(complianceRecipients);
  return <main className="min-h-screen bg-[#f4f7fb] text-slate-950"><div className="mx-auto max-w-[1280px] px-4 py-6 sm:px-6 lg:px-10 lg:py-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Reminders</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Family Reminders</h1><p className="mt-2 text-sm text-slate-500">See what is coming up, add a reminder, or manage who receives compliance emails.</p></div><button onClick={()=>setShowForm(true)} className="inline-flex items-center gap-2 rounded-2xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={17}/> Add reminder</button></header>
    {message&&<div className="mt-5 rounded-2xl border-2 border-slate-300 bg-white px-4 py-3 text-sm text-slate-700">{message}</div>}
    {showForm&&<section className="mt-6 rounded-[28px] border-2 border-blue-200 bg-white p-6"><div><h2 className="text-lg font-semibold">Add reminder</h2><p className="mt-1 text-sm text-slate-500">Choose the date, message and exactly who should receive it.</p></div><form onSubmit={saveReminder} className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Reminder name" value={title} onChange={setTitle} required/><Field label="Email subject" value={subject} onChange={setSubject} required/><label><span className="text-sm font-medium">Date and time</span><input required type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="mt-2 w-full rounded-xl border-2 border-slate-300 px-3 py-2.5"/></label><label><span className="text-sm font-medium">Repeat</span><select value={recurrence} onChange={e=>setRecurrence(e.target.value as Reminder["recurrence"])} className="mt-2 w-full rounded-xl border-2 border-slate-300 bg-white px-3 py-2.5"><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label className="md:col-span-2"><span className="text-sm font-medium">Email recipients</span><textarea rows={2} value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="family@example.com, another@example.com" className="mt-2 w-full rounded-xl border-2 border-slate-300 px-3 py-2.5"/><span className="mt-1 block text-xs text-slate-500">Separate multiple emails with commas, semicolons or new lines.</span></label><label className="md:col-span-2"><span className="text-sm font-medium">Message</span><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 w-full rounded-xl border-2 border-slate-300 px-3 py-2.5"/></label><div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl border-2 border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">{saving?"Saving...":"Save reminder"}</button></div></form></section>}
    <section className="mt-6 overflow-hidden rounded-[28px] border-2 border-slate-300 bg-white"><div className="flex items-center justify-between border-b-2 border-slate-200 px-5 py-5 sm:px-6"><div><h2 className="font-semibold">Upcoming reminders</h2><p className="mt-1 text-sm text-slate-500">Your scheduled one-time and repeating family reminders.</p></div><CalendarDays size={20} className="text-blue-600"/></div>{loading?<p className="px-6 py-8 text-sm text-slate-500">Loading reminders...</p>:reminders.length===0?<div className="px-6 py-10 text-center"><CalendarDays className="mx-auto text-slate-400" size={30}/><p className="mt-3 font-semibold">No reminders yet</p><p className="mt-1 text-sm text-slate-500">Use Add reminder whenever you want the family notified.</p></div>:<div className="divide-y-2 divide-slate-100">{reminders.map(r=><div key={r.id} className="grid gap-4 px-5 py-5 sm:px-6 md:grid-cols-[1.2fr_.7fr_1fr_auto] md:items-center"><div><p className="font-semibold">{r.title}</p><p className="mt-1 text-sm text-slate-500">{r.subject}</p>{r.notes&&<p className="mt-1 line-clamp-2 text-xs text-slate-400">{r.notes}</p>}</div><div><p className="text-xs uppercase tracking-wide text-slate-400">When</p><p className="mt-1 text-sm font-semibold">{new Date(r.starts_at).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{recurrenceLabels[r.recurrence]}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Email to</p><p className="mt-1 text-sm text-slate-700">{r.recipient_emails.length?r.recipient_emails.join(", "):"No recipients"}</p></div><button onClick={()=>remove(r.id)} className="rounded-xl border-2 border-slate-200 p-2 text-slate-500 hover:border-red-200 hover:text-red-600"><Trash2 size={16}/></button></div>)}</div>}</section>
    <section className="mt-6 rounded-[28px] border-2 border-slate-300 bg-white"><button onClick={()=>setShowEmailSettings(v=>!v)} className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Mail size={18}/></div><div><h2 className="font-semibold">Email Settings</h2><p className="mt-1 text-sm text-slate-500">Compliance reminders send 30, 7 and 2 days before due dates.</p></div></div><ChevronDown size={19} className={`transition ${showEmailSettings?"rotate-180":""}`}/></button>{showEmailSettings&&<div className="border-t-2 border-slate-200 px-5 py-5 sm:px-6"><div className="flex flex-wrap gap-2">{primaryEmail&&<span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700">Primary · {primaryEmail}</span>}{extras.map(email=><span key={email} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{email}</span>)}</div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto] md:items-end"><label><span className="text-sm font-medium">Additional compliance recipients</span><textarea rows={2} value={complianceRecipients} onChange={e=>setComplianceRecipients(e.target.value)} placeholder="spouse@example.com, accountant@example.com" className="mt-2 w-full rounded-xl border-2 border-slate-300 px-3 py-2.5"/></label><button onClick={saveRecipients} disabled={savingSettings} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white"><Save size={16}/>{savingSettings?"Saving...":"Save settings"}</button></div><div className="mt-4 flex gap-3 rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><Users size={18} className="mt-0.5 shrink-0"/><p>Your main account always receives compliance emails. Marking an item paid or completed stops future reminders for that item.</p></div></div>}</section>
  </div></main>;
}

function Field({label,value,onChange,required}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label><span className="text-sm font-medium">{label}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border-2 border-slate-300 px-3 py-2.5"/></label>}
