"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Building2, CalendarDays, CheckCircle2, ExternalLink, FileText, Home, Landmark, LogOut, Pencil, Plus, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Business={id:string;name:string;entity_type:string|null;state:string|null;entity_number:string|null;formation_date:string|null;secretary_of_state_url:string|null;notes:string|null;ein:string|null;tax_year_type:string;ca_annual_tax_applies:boolean;ca_additional_llc_fee_status:string};
type Obligation={id:string;business_id:string|null;title:string;category:string;amount_due:number|null;due_date:string;frequency:string|null;official_payment_url:string|null;status:string;notes:string|null};
const blankBusiness={name:"",entity_type:"LLC",state:"CA",entity_number:"",formation_date:"",secretary_of_state_url:"",notes:"",ein:"",tax_year_type:"calendar",ca_annual_tax_applies:false,ca_additional_llc_fee_status:"unknown"};
const blankObligation={title:"",category:"filing",amount_due:"",due_date:"",frequency:"yearly",official_payment_url:"",status:"upcoming",notes:""};
const money=(n:number|null)=>n==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
const dateLabel=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});

export default function BusinessesPage(){
  const router=useRouter();const supabase=useMemo(()=>createClient(),[]);
  const [businesses,setBusinesses]=useState<Business[]>([]);const [obligations,setObligations]=useState<Obligation[]>([]);const [businessForm,setBusinessForm]=useState(blankBusiness);const [editingBusiness,setEditingBusiness]=useState<string|null>(null);const [obligationBusinessId,setObligationBusinessId]=useState<string|null>(null);const [obligationForm,setObligationForm]=useState(blankObligation);const [editingObligation,setEditingObligation]=useState<string|null>(null);const [showBusinessForm,setShowBusinessForm]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  async function getUser(){for(let i=0;i<6;i++){const {data}=await supabase.auth.getSession();if(data.session?.user)return data.session.user;await new Promise(r=>setTimeout(r,150));}return null;}
  async function load(){setLoading(true);const user=await getUser();if(!user){router.replace("/");return;}const [b,o]=await Promise.all([supabase.from("businesses").select("id,name,entity_type,state,entity_number,formation_date,secretary_of_state_url,notes,ein,tax_year_type,ca_annual_tax_applies,ca_additional_llc_fee_status").order("created_at",{ascending:false}),supabase.from("obligations").select("id,business_id,title,category,amount_due,due_date,frequency,official_payment_url,status,notes").not("business_id","is",null).order("due_date",{ascending:true})]);if(b.error)setMessage(b.error.message);else setBusinesses((b.data??[]) as Business[]);if(o.error)setMessage(o.error.message);else setObligations((o.data??[]) as Obligation[]);setLoading(false);}
  useEffect(()=>{load();},[]);
  function addBusiness(){setEditingBusiness(null);setBusinessForm(blankBusiness);setShowBusinessForm(true);setMessage("");}
  function editBusiness(b:Business){setEditingBusiness(b.id);setBusinessForm({name:b.name,entity_type:b.entity_type??"",state:b.state??"",entity_number:b.entity_number??"",formation_date:b.formation_date??"",secretary_of_state_url:b.secretary_of_state_url??"",notes:b.notes??"",ein:b.ein??"",tax_year_type:b.tax_year_type??"calendar",ca_annual_tax_applies:b.ca_annual_tax_applies,ca_additional_llc_fee_status:b.ca_additional_llc_fee_status??"unknown"});setShowBusinessForm(true);window.scrollTo({top:0,behavior:"smooth"});}
  async function saveBusiness(e:FormEvent){e.preventDefault();setSaving(true);const user=await getUser();if(!user){router.replace("/");return;}const payload={name:businessForm.name.trim(),entity_type:businessForm.entity_type||null,state:businessForm.state||null,entity_number:businessForm.entity_number.trim()||null,formation_date:businessForm.formation_date||null,secretary_of_state_url:businessForm.secretary_of_state_url.trim()||null,notes:businessForm.notes.trim()||null,ein:businessForm.ein.trim()||null,tax_year_type:businessForm.tax_year_type,ca_annual_tax_applies:businessForm.ca_annual_tax_applies,ca_additional_llc_fee_status:businessForm.ca_additional_llc_fee_status,updated_at:new Date().toISOString()};const {error}=editingBusiness?await supabase.from("businesses").update(payload).eq("id",editingBusiness):await supabase.from("businesses").insert({user_id:user.id,...payload});if(error)setMessage(error.message);else{setShowBusinessForm(false);setEditingBusiness(null);setBusinessForm(blankBusiness);setMessage("Entity saved.");await load();}setSaving(false);}
  async function deleteBusiness(id:string){if(!confirm("Delete this business and its linked compliance items?"))return;const {error}=await supabase.from("businesses").delete().eq("id",id);if(error)setMessage(error.message);else await load();}
  function addObligation(id:string){setObligationBusinessId(id);setEditingObligation(null);setObligationForm(blankObligation);}
  function editObligation(o:Obligation){setObligationBusinessId(o.business_id);setEditingObligation(o.id);setObligationForm({title:o.title,category:o.category,amount_due:o.amount_due==null?"":String(o.amount_due),due_date:o.due_date,frequency:o.frequency??"",official_payment_url:o.official_payment_url??"",status:o.status,notes:o.notes??""});}
  async function saveObligation(e:FormEvent){e.preventDefault();if(!obligationBusinessId)return;setSaving(true);const user=await getUser();if(!user){router.replace("/");return;}const amount=obligationForm.amount_due.trim()?Number(obligationForm.amount_due):null;const payload={business_id:obligationBusinessId,title:obligationForm.title.trim(),category:obligationForm.category,due_date:obligationForm.due_date,amount_due:Number.isFinite(amount)?amount:null,frequency:obligationForm.frequency||null,official_payment_url:obligationForm.official_payment_url.trim()||null,status:obligationForm.status,notes:obligationForm.notes.trim()||null,updated_at:new Date().toISOString()};const {error}=editingObligation?await supabase.from("obligations").update(payload).eq("id",editingObligation):await supabase.from("obligations").insert({user_id:user.id,...payload});if(error)setMessage(error.message);else{setObligationBusinessId(null);setEditingObligation(null);setObligationForm(blankObligation);setMessage("Compliance item saved.");await load();}setSaving(false);}
  async function deleteObligation(id:string){if(!confirm("Delete this compliance item?"))return;const {error}=await supabase.from("obligations").delete().eq("id",id);if(error)setMessage(error.message);else await load();}
  async function signOut(){await supabase.auth.signOut();router.replace("/");}

  const now=new Date();const quarterEnd=new Date(now.getFullYear(),Math.floor(now.getMonth()/3)*3+3,0);const dueThisQuarter=obligations.filter(o=>{const d=new Date(`${o.due_date}T12:00:00`);return d>=now&&d<=quarterEnd&&o.status!=="completed";}).length;const caCount=businesses.filter(b=>b.state?.toUpperCase()==="CA").length;const otherCount=businesses.length-caCount;

  return <main className="min-h-screen bg-[#f7f9fc] text-slate-950"><div className="mx-auto flex min-h-screen max-w-[1600px]">
    <Sidebar signOut={signOut}/>
    <section className="min-w-0 flex-1 px-5 py-6 md:px-8 lg:px-10">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-violet-600">Entity management</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Business Compliance</h1><p className="mt-2 text-sm text-slate-500">Track each LLC, corporation, filing, tax, renewal and official deadline.</p></div><button onClick={addBusiness} className="inline-flex items-center gap-2 rounded-2xl bg-blue-600 px-4 py-3 text-sm font-medium text-white shadow-sm"><Plus size={17}/> Add entity</button></div>
      {message&&<div className="mt-5 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div>}
      <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Building2} label="Total Entities" value={businesses.length} sub="Active entities" tone="blue"/><Metric icon={CalendarDays} label="Due This Quarter" value={dueThisQuarter} sub="Open filings" tone="amber"/><Metric icon={Landmark} label="California Entities" value={caCount} sub="CA entities" tone="green"/><Metric icon={FileText} label="Other States" value={otherCount} sub="Non-CA entities" tone="violet"/></div>

      {showBusinessForm&&<section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">{editingBusiness?"Edit entity":"Add business entity"}</h2><form onSubmit={saveBusiness} className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Entity name" required value={businessForm.name} onChange={v=>setBusinessForm({...businessForm,name:v})}/><Select label="Entity type" value={businessForm.entity_type} onChange={v=>setBusinessForm({...businessForm,entity_type:v})} options={["LLC","Corporation","S Corporation","Partnership","Sole Proprietorship","Trust","Other"]}/><Field label="State" value={businessForm.state} onChange={v=>setBusinessForm({...businessForm,state:v})}/><Field label="Entity / SOS number" value={businessForm.entity_number} onChange={v=>setBusinessForm({...businessForm,entity_number:v})}/><Field label="Formation date" type="date" value={businessForm.formation_date} onChange={v=>setBusinessForm({...businessForm,formation_date:v})}/><Field label="EIN" value={businessForm.ein} onChange={v=>setBusinessForm({...businessForm,ein:v})}/><Field label="Secretary of State / official entity URL" type="url" value={businessForm.secretary_of_state_url} onChange={v=>setBusinessForm({...businessForm,secretary_of_state_url:v})}/><Select label="Tax year" value={businessForm.tax_year_type} onChange={v=>setBusinessForm({...businessForm,tax_year_type:v})} options={["calendar","fiscal"]}/><label className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4"><input type="checkbox" checked={businessForm.ca_annual_tax_applies} onChange={e=>setBusinessForm({...businessForm,ca_annual_tax_applies:e.target.checked})}/><span className="text-sm">California $800 annual LLC tax applies</span></label><Select label="CA additional LLC fee" value={businessForm.ca_additional_llc_fee_status} onChange={v=>setBusinessForm({...businessForm,ca_additional_llc_fee_status:v})} options={["unknown","not_applicable","may_apply","applies","paid"]}/><label className="md:col-span-2"><span className="text-sm font-medium text-slate-700">Notes</span><textarea rows={3} value={businessForm.notes} onChange={e=>setBusinessForm({...businessForm,notes:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-300 px-3 py-2.5"/></label><div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={()=>setShowBusinessForm(false)} className="rounded-2xl border border-slate-200 px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="rounded-2xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white">{saving?"Saving...":"Save entity"}</button></div></form></section>}

      <div className="mt-6 space-y-5">{loading?<p className="text-sm text-slate-500">Loading business compliance...</p>:businesses.length===0?<section className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><Building2 className="mx-auto text-slate-400"/><h2 className="mt-3 font-semibold">No entities yet</h2><p className="mt-1 text-sm text-slate-500">Add each LLC, corporation, trust or other entity here.</p></section>:businesses.map(b=>{const items=obligations.filter(o=>o.business_id===b.id);const next=items.filter(i=>i.status!=="completed").sort((a,b)=>a.due_date.localeCompare(b.due_date))[0];return <article key={b.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 px-6 py-5"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-violet-50 text-violet-600"><Building2 size={21}/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{b.name}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{b.entity_type||"Entity"}</span>{b.state&&<span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700">{b.state}</span>}</div><p className="mt-1 text-sm text-slate-500">{b.entity_number?`Entity # ${b.entity_number}`:"No entity number"}{b.ein?` · EIN ${b.ein}`:""}</p>{b.ca_annual_tax_applies&&<p className="mt-2 text-xs font-medium text-amber-700">California $800 annual LLC tax applies</p>}</div></div><div className="flex flex-wrap items-center gap-2">{next&&<div className="mr-2 rounded-2xl bg-amber-50 px-4 py-2 text-right"><p className="text-xs text-amber-600">Next due</p><p className="text-sm font-semibold text-amber-900">{dateLabel(next.due_date)}</p></div>}{b.secretary_of_state_url&&<a href={b.secretary_of_state_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 p-2 text-slate-500"><ExternalLink size={15}/></a>}<button onClick={()=>editBusiness(b)} className="rounded-xl border border-slate-200 p-2 text-slate-500"><Pencil size={15}/></button><button onClick={()=>deleteBusiness(b.id)} className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:text-red-600"><Trash2 size={15}/></button></div></div>
        <div className="px-6 py-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Compliance items</h3><p className="mt-1 text-sm text-slate-500">Taxes, filings, renewals, licenses and reminders for this entity.</p></div><button onClick={()=>addObligation(b.id)} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white"><Plus size={15}/> Add item</button></div>{items.length===0?<p className="rounded-2xl bg-slate-50 px-4 py-5 text-sm text-slate-500">No compliance items yet.</p>:<div className="grid gap-3">{items.map(o=><div key={o.id} className="grid gap-3 rounded-2xl border border-slate-100 bg-slate-50/60 p-4 md:grid-cols-[1.35fr_.8fr_.8fr_auto] md:items-center"><div><div className="flex items-center gap-2"><CheckCircle2 size={16} className={o.status==="completed"?"text-emerald-500":"text-slate-300"}/><p className="text-sm font-semibold">{o.title}</p></div><p className="mt-1 pl-6 text-xs text-slate-500">{o.category}{o.frequency?` · ${o.frequency}`:""}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Due</p><p className="mt-1 text-sm font-medium">{dateLabel(o.due_date)}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Status / amount</p><p className="mt-1 text-sm font-medium">{o.status} · {money(o.amount_due)}</p></div><div className="flex gap-2">{o.official_payment_url&&<a href={o.official_payment_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 bg-white p-2"><ExternalLink size={14}/></a>}<button onClick={()=>editObligation(o)} className="rounded-xl border border-slate-200 bg-white p-2"><Pencil size={14}/></button><button onClick={()=>deleteObligation(o.id)} className="rounded-xl border border-slate-200 bg-white p-2"><Trash2 size={14}/></button></div></div>)}</div>}</div>
      </article>})}</div>
    </section>
  </div>

  {obligationBusinessId&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={saveObligation} className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-semibold">{editingObligation?"Edit compliance item":"Add compliance item"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Title" required value={obligationForm.title} onChange={v=>setObligationForm({...obligationForm,title:v})}/><Select label="Category" value={obligationForm.category} onChange={v=>setObligationForm({...obligationForm,category:v})} options={["filing","tax","license","renewal","insurance","registered_agent","other"]}/><Field label="Due date" required type="date" value={obligationForm.due_date} onChange={v=>setObligationForm({...obligationForm,due_date:v})}/><Select label="Frequency" value={obligationForm.frequency} onChange={v=>setObligationForm({...obligationForm,frequency:v})} options={["one-time","monthly","quarterly","yearly"]}/><Field label="Amount due" type="number" value={obligationForm.amount_due} onChange={v=>setObligationForm({...obligationForm,amount_due:v})}/><Select label="Status" value={obligationForm.status} onChange={v=>setObligationForm({...obligationForm,status:v})} options={["upcoming","due_soon","paid","completed","past_due"]}/><Field label="Official payment / filing URL" type="url" value={obligationForm.official_payment_url} onChange={v=>setObligationForm({...obligationForm,official_payment_url:v})}/><label><span className="text-sm font-medium text-slate-700">Notes</span><textarea rows={3} value={obligationForm.notes} onChange={e=>setObligationForm({...obligationForm,notes:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-300 px-3 py-2.5"/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setObligationBusinessId(null)} className="rounded-2xl border border-slate-200 px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="rounded-2xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white">{saving?"Saving...":"Save compliance item"}</button></div></form></div>}
  </main>;
}

function Sidebar({signOut}:{signOut:()=>void}){const nav=[{href:"/dashboard",label:"Dashboard",icon:Home},{href:"/properties",label:"Properties & Taxes",icon:Landmark},{href:"/businesses",label:"Business Compliance",icon:Building2},{href:"/reminders",label:"Family Reminders",icon:CalendarDays}];return <aside className="hidden w-72 shrink-0 border-r border-slate-200 bg-white px-5 py-6 lg:flex lg:flex-col"><Link href="/dashboard" className="flex items-center gap-3 px-2"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 text-white"><Home size={21}/></div><div><p className="font-semibold">Vo Family Operations</p><p className="text-xs text-slate-500">Family Dashboard</p></div></Link><nav className="mt-9 space-y-2">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-medium ${href==="/businesses"?"bg-blue-50 text-blue-700":"text-slate-600 hover:bg-slate-50"}`}><Icon size={18}/>{label}</Link>)}</nav><button onClick={signOut} className="mt-auto flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3 text-sm text-slate-600"><LogOut size={17}/> Sign out</button></aside>}
function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="text-sm font-medium text-slate-700">{label}</span><input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-300 px-3 py-2.5 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label><span className="text-sm font-medium text-slate-700">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-300 bg-white px-3 py-2.5">{options.map(o=><option key={o} value={o}>{o.replaceAll("_"," ")}</option>)}</select></label>}
function Metric({icon:Icon,label,value,sub,tone}:{icon:any;label:string;value:number;sub:string;tone:string}){const tones:any={blue:"border-sky-200 bg-sky-50 text-sky-700",amber:"border-amber-200 bg-amber-50 text-amber-700",green:"border-emerald-200 bg-emerald-50 text-emerald-700",violet:"border-violet-200 bg-violet-50 text-violet-700"};return <div className={`rounded-2xl border p-4 ${tones[tone]}`}><div className="flex items-center justify-between"><Icon size={19}/><span className="text-2xl font-semibold text-slate-950">{value}</span></div><p className="mt-3 text-sm font-semibold">{label}</p><p className="mt-0.5 text-xs opacity-70">{sub}</p></div>}
