"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Clock3, ShieldCheck, UserCheck, UserX } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Profile={id:string;email:string|null;approved:boolean;is_admin:boolean;approval_requested_at:string;approved_at:string|null};

export default function AccountApprovalsPage(){
  const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  async function load(){setLoading(true);const {data:sessionData}=await supabase.auth.getSession();const user=sessionData.session?.user;if(!user){router.replace("/");return;}const {data:me}=await supabase.from("profiles").select("approved,is_admin").eq("id",user.id).maybeSingle();if(!me?.approved||!me?.is_admin){router.replace("/dashboard");return;}const {data,error}=await supabase.from("profiles").select("id,email,approved,is_admin,approval_requested_at,approved_at").order("approved",{ascending:true}).order("approval_requested_at",{ascending:true});if(error)setMessage(error.message);else setProfiles((data??[]) as Profile[]);setLoading(false);}
  useEffect(()=>{load();},[]);
  async function setApproval(profile:Profile,approved:boolean){setMessage("");const {data}=await supabase.auth.getSession();const adminId=data.session?.user.id;if(!adminId){router.replace("/");return;}if(profile.is_admin&&!approved){setMessage("The administrator account cannot be revoked here.");return;}const {error}=await supabase.from("profiles").update({approved,approved_at:approved?new Date().toISOString():null,approved_by:approved?adminId:null,updated_at:new Date().toISOString()}).eq("id",profile.id);if(error)setMessage(error.message);else{setMessage(approved?`${profile.email??"Account"} approved.`:`${profile.email??"Account"} access revoked.`);await load();}}
  const pending=profiles.filter(p=>!p.approved);const approved=profiles.filter(p=>p.approved);
  return <main className="min-h-screen bg-[#f4f7fb] text-slate-950"><div className="mx-auto max-w-[1180px] px-4 py-6 sm:px-6 lg:px-10 lg:py-8">
    <header><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-blue-600"><ShieldCheck size={16}/> Admin only</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Account Approvals</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Keep this simple: approve people you recognize, and revoke access when someone should no longer see private family data.</p></header>
    {message&&<div className="mt-5 rounded-2xl border-2 border-slate-300 bg-white px-4 py-3 text-sm text-slate-700">{message}</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-[24px] border-2 border-amber-300 bg-amber-50 p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><Clock3 size={19}/></div><div><p className="text-sm font-medium text-amber-800">Waiting for approval</p><p className="text-3xl font-semibold text-amber-950">{pending.length}</p></div></div></div><div className="rounded-[24px] border-2 border-emerald-300 bg-emerald-50 p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700"><CheckCircle2 size={19}/></div><div><p className="text-sm font-medium text-emerald-800">Approved accounts</p><p className="text-3xl font-semibold text-emerald-950">{approved.length}</p></div></div></div></div>
    <section className="mt-6 overflow-hidden rounded-[28px] border-2 border-slate-300 bg-white"><div className="border-b-2 border-slate-200 px-5 py-5 sm:px-6"><h2 className="font-semibold">Pending requests</h2><p className="mt-1 text-sm text-slate-500">Only approve someone you know and trust.</p></div>{loading?<p className="px-6 py-8 text-sm text-slate-500">Loading account requests...</p>:pending.length===0?<div className="px-6 py-10 text-center"><CheckCircle2 className="mx-auto text-emerald-500" size={28}/><p className="mt-3 font-semibold">No requests waiting.</p></div>:<div className="divide-y-2 divide-slate-100">{pending.map(profile=><div key={profile.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-6"><div><p className="font-semibold">{profile.email??"No email"}</p><p className="mt-1 text-xs text-slate-500">Requested {new Date(profile.approval_requested_at).toLocaleString()}</p></div><button onClick={()=>setApproval(profile,true)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-700"><UserCheck size={16}/> Approve access</button></div>)}</div>}</section>
    <section className="mt-6 overflow-hidden rounded-[28px] border-2 border-slate-300 bg-white"><div className="border-b-2 border-slate-200 px-5 py-5 sm:px-6"><h2 className="font-semibold">Approved accounts</h2><p className="mt-1 text-sm text-slate-500">People who can currently access the private dashboard.</p></div><div className="divide-y-2 divide-slate-100">{approved.map(profile=><div key={profile.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2"><p className="font-semibold">{profile.email??"No email"}</p>{profile.is_admin&&<span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">Administrator</span>}</div><p className="mt-1 text-xs text-slate-500">{profile.approved_at?`Approved ${new Date(profile.approved_at).toLocaleString()}`:"Approved"}</p></div>{!profile.is_admin&&<button onClick={()=>setApproval(profile,false)} className="inline-flex items-center gap-2 rounded-xl border-2 border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100"><UserX size={16}/> Revoke access</button>}</div>)}</div></section>
  </div></main>;
}
